apiVersion: apps/v1
kind: Deployment
metadata:
  name: shadowsocks
spec:
  template:
    spec:
      containers:
      - name: shadowsocks
        image: mazy/ss-v2ry
        env:
        - {name: PASSWORD, value: changeme-iebohthaedoo9eK0kaiveowo4af9phee}
