---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: shadowsocks
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 500m
    ingress.kubernetes.io/proxy-body-size: 500m
spec:
  rules:
    - host: shadowsocks.your-domain.tld
      http:
        paths:
          - backend:
              serviceName: shadowsocks
              servicePort: 1080
            path: /
